name: Container Jobs

on: 
  push:
  workflow_dispatch:

jobs:
  Container:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
#      - name: Check out repository
#        uses: actions/checkout@v2

      - name: List environmental variables
        run: env

  Native:
    runs-on: ubuntu-latest
    steps:
#      - name: Check out repository
#        uses: actions/checkout@v2

      - name: List environmental variables
        run: env
        
  Self-Hosted:
    runs-on: self-hosted
    steps:
#      - name: Check out repository
#        uses: actions/checkout@v2

      - name: List environmental variables
        run: env        
