# demo re-usable

name: Demo 01 - Basic Workflow

on:
  workflow_call:
    inputs:
      name:
        description: 'Person to greet'
        type: string
        default: 'World'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on, in this case a Linus hosted runner
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello reusable ${{ inputs.name }}" # Outputs the input parameter, by accessing the github context object
